name: gmq580_ps_mg
channels:
  - conda-forge
dependencies:
  - python=3.10
  - osmnx
  - networkx
  - geopandas
  - pandas
  - shapely
  - pyproj
  - rtree
  - mapclassify
  - folium
  - matplotlib
  - spopt
  - pyyaml
  - pytest
  - pytest-cov
  - pip