name: gmq580
channels:
  - conda-forge
dependencies:
  - python=3.10
  - osmnx
  - networkx
  - geopandas
  - pandas
  - shapely
  - pyproj
  - folium
  - matplotlib
  - spopt
  - pyyaml
  - pytest
  - pytest-cov
  - pip